name: Danger CI

on:
  pull_request:

jobs:
  danger:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
          node-version: 22 # ✅ Cocok dengan engines.node di package.json
          cache: 'pnpm'

      - uses: pnpm/action-setup@v2
        with:
          version: 9
          run_install: false  # Kita kontrol install sendiri

      - name: Restore pnpm cache
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - run: pnpm install --frozen-lockfile

      - name: Run Danger
        run: pnpm danger ci --dangerfile dangerfile.ts
        env:
          DANGER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
